package model;
// Generated 2020�~11��11�� �U��1:56:13 by Hibernate Tools 5.4.21.Final

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer id;
	private String r1;
	private String r2;
	private String r3;
	private String r4;
	private String r5;
	private String rsum;
	private String rsales;
	private String rcost;

	public Menu() {
	}

	public Menu(String r1, String r2, String r3, String r4, String r5, String rsum, String rsales, String rcost) {
		this.r1 = r1;
		this.r2 = r2;
		this.r3 = r3;
		this.r4 = r4;
		this.r5 = r5;
		this.rsum = rsum;
		this.rsales = rsales;
		this.rcost = rcost;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getR1() {
		return this.r1;
	}

	public void setR1(String r1) {
		this.r1 = r1;
	}

	public String getR2() {
		return this.r2;
	}

	public void setR2(String r2) {
		this.r2 = r2;
	}

	public String getR3() {
		return this.r3;
	}

	public void setR3(String r3) {
		this.r3 = r3;
	}

	public String getR4() {
		return this.r4;
	}

	public void setR4(String r4) {
		this.r4 = r4;
	}

	public String getR5() {
		return this.r5;
	}

	public void setR5(String r5) {
		this.r5 = r5;
	}

	public String getRsum() {
		return this.rsum;
	}

	public void setRsum(String rsum) {
		this.rsum = rsum;
	}

	public String getRsales() {
		return this.rsales;
	}

	public void setRsales(String rsales) {
		this.rsales = rsales;
	}

	public String getRcost() {
		return this.rcost;
	}

	public void setRcost(String rcost) {
		this.rcost = rcost;
	}

}
